// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model holds the UI-facing read types. tygo generates
web/src/lib/model.gen.ts from this package (make types), so every field
here is part of the wire contract with the frontend.
*/

/**
 * Pool is one StoragePool flattened for the UI: spec identity, agent-observed
 * host state, and the operator's availability verdict in one row.
 */
export interface Pool {
  name: string;
  node: string;
  raid: string;
  devices: Device[];
  vg: string;
  capacityBytes: number /* int64 */;
  freeBytes: number /* int64 */;
  health: string; // Online | Degraded | Failed | Unknown
  available: boolean;
  reason: string; // Available condition reason; explains false
  linstor: string;
}
/**
 * Device is one backing disk's observed state.
 */
export interface Device {
  path: string;
  state: string; // InSync | Rebuilding | Failed | Missing
  smart: string;
}
/**
 * Node is one cluster member.
 */
export interface Node {
  name: string;
  ready: boolean;
  roles: string[];
  addresses: string[];
  kubeletVersion: string;
}
/**
 * Volume is one PVC: the unit everything else references (LUNs, shares,
 * VM disks all point at PVCs).
 */
export interface Volume {
  namespace: string;
  name: string;
  storageClass: string;
  phase: string;
  capacityBytes: number /* int64 */;
  block: boolean;
}
/**
 * Share is one NFS/SMB export: spec identity plus the operator's placement
 * and the agent's export state.
 */
export interface Share {
  namespace: string;
  name: string;
  claim: string;
  nfs: boolean;
  smb: boolean;
  node: string;
  state: string; // Pending | Exported | Failed
  available: boolean;
  reason: string;
}
/**
 * Snapshot is one consistent frame of everything the UI shows; the WS hub
 * sends a full frame per change rather than diffs.
 */
export interface Snapshot {
  pools: Pool[];
  nodes: Node[];
  volumes: Volume[];
  shares: Share[];
}
