// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model holds the UI-facing read types. tygo generates
web/src/lib/model.gen.ts from this package (make types), so every field
here is part of the wire contract with the frontend.
*/

/**
 * Pool is one StoragePool flattened for the UI: spec identity, agent-observed
 * host state, and the operator's availability verdict in one row.
 */
export interface Pool {
  name: string;
  node: string;
  raid: string;
  devices: Device[];
  vg: string;
  capacityBytes: number /* int64 */;
  freeBytes: number /* int64 */;
  health: string; // Online | Degraded | Failed | Unknown
  available: boolean;
  reason: string; // Available condition reason; explains false
  linstor: string;
}
/**
 * Device is one backing disk's observed state.
 */
export interface Device {
  path: string;
  state: string; // InSync | Rebuilding | Failed | Missing
  smart: string;
}
/**
 * Node is one cluster member.
 */
export interface Node {
  name: string;
  ready: boolean;
  roles: string[];
  addresses: string[];
  kubeletVersion: string;
  disks: Disk[];
}
/**
 * Disk is one observed block device on a node; unclaimed disks feed the
 * create-pool form.
 */
export interface Disk {
  path: string;
  model: string;
  serial: string;
  sizeBytes: number /* int64 */;
  rotational: boolean;
  claimed: boolean;
}
/**
 * Volume is one PVC: the unit everything else references (LUNs, shares,
 * VM disks all point at PVCs). Resource is the bound PV name, which is
 * also the LINSTOR resource name for CSI-provisioned volumes.
 */
export interface Volume {
  namespace: string;
  name: string;
  storageClass: string;
  phase: string;
  capacityBytes: number /* int64 */;
  block: boolean;
  resource: string;
  replication?: Replication;
}
/**
 * Replication is the DRBD view of one volume, absent for non-replicated
 * or unresolved volumes.
 */
export interface Replication {
  replicas: Replica[];
}
/**
 * Replica is one node's copy: disk state (UpToDate, Inconsistent,
 * SyncTarget...) and whether the node currently holds the resource open.
 * SyncPercent is set only while a resync runs, in whole percent so a
 * running sync does not push a frame per decimal tick.
 */
export interface Replica {
  node: string;
  diskState: string;
  inUse: boolean;
  syncPercent?: number /* int */;
}
/**
 * Share is one NFS/SMB export: spec identity plus the operator's placement
 * and the agent's export state.
 */
export interface Share {
  namespace: string;
  name: string;
  claim: string;
  nfs: boolean;
  smb: boolean;
  node: string;
  state: string; // Pending | Exported | Failed
  available: boolean;
  reason: string;
}
/**
 * Target is one iSCSI target: spec identity plus the operator's placement
 * and the agent's LIO state.
 */
export interface Target {
  namespace: string;
  name: string;
  iqn: string;
  vip: string;
  activeNode: string;
  sessions: number /* int32 */;
  state: string; // Pending | Exported | Failed
  luns: TargetLUN[];
  available: boolean;
  reason: string;
}
/**
 * TargetLUN is one logical unit: the claim it exposes and the device the
 * operator resolved for the agent.
 */
export interface TargetLUN {
  id: number /* int32 */;
  claim: string;
  device: string;
}
/**
 * VolumeSnapshot is one CSI snapshot of a volume.
 */
export interface VolumeSnapshot {
  namespace: string;
  name: string;
  source: string; // source PVC name
  ready: boolean;
  sizeBytes: number /* int64 */;
  createdAt: string; // RFC3339; empty until bound
}
/**
 * Alert is one Warning event: the appliance's trouble feed. Kubernetes
 * aggregates repeats, so Count and LastSeen carry the recurrence story.
 */
export interface Alert {
  namespace: string;
  object: string; // Kind/name of the involved object
  reason: string;
  message: string;
  count: number /* int32 */;
  lastSeen: string; // RFC3339
}
/**
 * Task is one recorded admin action: the appliance's audit trail, newest
 * first, in-memory only (reboot starts it fresh).
 */
export interface Task {
  verb: string;
  object: string;
  by: string;
  ok: boolean;
  at: string; // RFC3339
}
/**
 * Snapshot is one consistent frame of everything the UI shows; the WS hub
 * sends a full frame per change rather than diffs.
 */
export interface Snapshot {
  pools: Pool[];
  nodes: Node[];
  volumes: Volume[];
  shares: Share[];
  targets: Target[];
  snapshots: VolumeSnapshot[];
  alerts: Alert[];
  tasks: Task[];
}
