apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/storage.stornas.io_storagepools.yaml
  - crd/storage.stornas.io_targets.yaml
  - crd/storage.stornas.io_shares.yaml
  - crd/storage.stornas.io_localusers.yaml
  - linstorcluster.yaml
  - linstorsatellite.yaml
  - storageclasses.yaml
  - snapshotclass.yaml
  - agent.yaml
  - operator.yaml
  - server.yaml
